pr:
  branches:
    include:
    - '*'
  paths:
    exclude:
    - 'docs/*'

resources:
  containers:
  - container:
    image: azpagentinfra/arm:latest
  - container: dotnetcore_centos6
    image: azpagentinfra/centos6:latest

jobs:

################################################################################
- job: build_windows_x64_agent
################################################################################
  displayName: Windows Agent (x64)
  pool:
    vmImage: vs2017-win2016
  steps:

  # Steps template for windows platform
  - template: .vsts.template.windows.yml
    parameters:
      componentDetection: 'true'
      testLogTitle: 'Windows-x64'

  - script: dotnet tool install --global dotnet-reportgenerator-globaltool
    displayName: Install Report Generator

  - script: dev.cmd report
    displayName: Generate Code Coverage report
    workingDirectory: src

  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: 'cobertura'
      summaryFileLocation: _reports/**/Cobertura.xml
      pathToSources: src

  # Package .NET Core Windows dependency (VC++ Redistributable)
  - template: .azure-pipelines/package-vcredist.yml
    parameters:
      layoutRoot: '_layout/win-x64'
      flavor: 'x64'
      condition: and(succeeded(), ne(variables['build.reason'], 'PullRequest'))

  # Create agent package zip
  - script: dev.cmd package Release
    workingDirectory: src
    displayName: Package Release
    condition: and(succeeded(), ne(variables['build.reason'], 'PullRequest'))

  # Upload agent package zip as build artifact
  - task: PublishBuildArtifacts@1
    displayName: Publish Artifact (Windows x64)
    condition: and(succeeded(), ne(variables['build.reason'], 'PullRequest'))
    inputs:
      pathToPublish: _package
      artifactName: agent
      artifactType: container

################################################################################
- job: build_windows_x86_agent
################################################################################
  displayName: Windows Agent (x86)
  pool:
    name: buildDevs
    demands: 'Agent.OSArchitecture -equals X86'
  steps:

  # Steps template for windows platform
  - template: .vsts.template.windows.yml
    parameters:
      testLogTitle: 'Windows-x86'

  # Package .NET Core Windows dependency (VC++ Redistributable)
  - template: .azure-pipelines/package-vcredist.yml
    parameters:
      layoutRoot: '_layout/win-x86'
      flavor: 'x86'
      condition: and(succeeded(), ne(variables['build.reason'], 'PullRequest'))

  # Create agent package zip
  - script: dev.cmd package Release
    workingDirectory: src
    displayName: Package Release
    condition: and(succeeded(), ne(variables['build.reason'], 'PullRequest'))

  # Upload agent package zip as build artifact
  - task: PublishBuildArtifacts@1
    displayName: Publish Artifact (Windows x86)
    condition: and(succeeded(), ne(variables['build.reason'], 'PullRequest'))
    inputs:
      pathToPublish: _package
      artifactName: agent
      artifactType: container

################################################################################
- job: build_linux_x64_agent
################################################################################
  displayName: Linux Agent (x64)
  pool:
    vmImage: ubuntu-16.04
  steps:

  # Steps template for non-windows platform
  - template: .vsts.template.nonwindows.yml
    parameters:
      componentDetection: 'true'
      testLogTitle: 'Linux-x64'
      enableADOLogIssue: 'true'

  # Create agent package zip
  - script: ./dev.sh package Release
    workingDirectory: src
    displayName: Package Release
    condition: and(succeeded(), ne(variables['build.reason'], 'PullRequest'))

  # Upload agent package zip as build artifact
  - task: PublishBuildArtifacts@1
    displayName: Publish Artifact (Linux x64)
    condition: and(succeeded(), ne(variables['build.reason'], 'PullRequest'))
    inputs:
      pathToPublish: _package
      artifactName: agent
      artifactType: container

################################################################################
- job: build_linux_arm_agent
################################################################################
  displayName: Linux Agent (ARM)
  pool:
    name: buildDevs
    demands: 'Agent.OSArchitecture -equals ARM'
  container: dotnetcore_arm
  timeoutInMinutes: 75
  steps:

  # Steps template for non-windows platform
  - template: .vsts.template.nonwindows.yml
    parameters:
      testLogTitle: 'Linux-ARM'

  # Create agent package zip
  - script: ./dev.sh package Release
    workingDirectory: src
    displayName: Package Release
    condition: and(succeeded(), ne(variables['build.reason'], 'PullRequest'))

  # Upload agent package zip as build artifact
  - task: PublishBuildArtifacts@1
    displayName: Publish Artifact (Linux ARM)
    condition: and(succeeded(), ne(variables['build.reason'], 'PullRequest'))
    inputs:
      pathToPublish: _package
      artifactName: agent
      artifactType: container

################################################################################
- job: build_rhel6_x64_agent
################################################################################
  displayName: RHEL6 Agent (x64)
  pool:
    vmImage: ubuntu-16.04
  container: dotnetcore_centos6
  steps:

  # Steps template for non-windows platform
  - template: .vsts.template.nonwindows.yml
    parameters:
      testLogTitle: 'RHEL-x64'

  # Create agent package zip
  - script: ./dev.sh package Release
    workingDirectory: src
    displayName: Package Release
    condition: and(succeeded(), ne(variables['build.reason'], 'PullRequest'))

  # Upload agent package zip as build artifact
  - task: PublishBuildArtifacts@1
    displayName: Publish Artifact (RHEL6 x64)
    condition: and(succeeded(), ne(variables['build.reason'], 'PullRequest'))
    inputs:
      pathToPublish: _package
      artifactName: agent
      artifactType: container

################################################################################
- job: build_osx_agent
################################################################################
  displayName: macOS Agent (x64)
  pool:
    vmImage: macOS-10.14
  steps:

  # Steps template for non-windows platform
  - template: .vsts.template.nonwindows.yml
    parameters:
      componentDetection: 'true'
      testLogTitle: 'macOS-x64'

  # Create agent package zip
  - script: ./dev.sh package Release
    workingDirectory: src
    displayName: Package Release
    condition: and(succeeded(), ne(variables['build.reason'], 'PullRequest'))

  # Upload agent package zip as build artifact
  - task: PublishBuildArtifacts@1
    displayName: Publish Artifact (OSX)
    condition: and(succeeded(), ne(variables['build.reason'], 'PullRequest'))
    inputs:
      pathToPublish: _package
      artifactName: agent
      artifactType: container

################################################################################
- job: build_linux_arm_on_x64_agent
################################################################################
  displayName: Linux Agent (ARM on x64 EXPERIMENTAL)
  pool:
    vmImage: ubuntu-16.04
  steps:

  # Steps template for non-windows platform
  - template: .vsts.template.nonwindows.yml
    parameters:
      componentDetection: 'true'
      testLogTitle: 'Linux-ARM-on-x64'
      targetRuntime: 'linux-arm'
      skipTests: 'true'

  - task: PublishBuildArtifacts@1
    displayName: Publish Layout Directory
    condition: succeeded()
    inputs:
      pathToPublish: _layout
      artifactName: _layout-linux-arm-$(System.BuildId)
      artifactType: container

################################################################################
- job: test_linux_arm_built_on_x64_agent
################################################################################
  displayName: Linux Agent (Testing ARM Built On x64 EXPERIMENTAL)
  dependsOn: build_linux_arm_on_x64_agent
  pool:
    name: buildDevs
    demands: 'Agent.OSArchitecture -equals ARM'
  container: dotnetcore_arm
  timeoutInMinutes: 75
  steps:

  - task: DownloadBuildArtifacts@0
    displayName: Download Layout Directory
    inputs:
      downloadPath: _layout
      artifactName: _layout-linux-arm-$(System.BuildId)

  # Run test
  - script: ./dev.sh test
    workingDirectory: src
    displayName: Test

  # Publish test results
  - task: PublishTestResults@2
    displayName: Publish Test Results **/*.trx
    condition: always()
    inputs:
      testRunner: VSTest
      testResultsFiles: '**/*.trx'
      testRunTitle: 'Agent Tests - ARM-BuiltOn-x64'

  # Upload test log
  - task: PublishBuildArtifacts@1
    displayName: Publish Test logs
    condition: always()
    inputs:
      pathToPublish: src/Test/TestLogs
      artifactName: ARM-BuiltOn-x64-$(System.JobId)
      artifactType: container


  # # Create agent package zip
  # - script: ./dev.sh package Release
  #   workingDirectory: src
  #   displayName: Package Release
  #   condition: and(succeeded(), ne(variables['build.reason'], 'PullRequest'))

  # # Upload agent package zip as build artifact
  # - task: PublishBuildArtifacts@1
  #   displayName: Publish Artifact (Linux x64)
  #   condition: and(succeeded(), ne(variables['build.reason'], 'PullRequest'))
  #   inputs:
  #     pathToPublish: _package
  #     artifactName: agent
  #     artifactType: container